### ISSUE TITLE
Column tipo_meio is raising an exception when not filled

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#292]
So we have to

- [x] Create a failing test for this scenario
- [x] Fix it

This is the corresponding on laravel.log:

````
[2018-04-25 12:11:11] production.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "tipo_meio_id" violates not-null constraint
DETAIL:  Failing row contains (397, 5936, 5085, 2, null, 2014-05-24 00:00:00, 2, 9, null, 9, MESA DA ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO, PRESIDENTE DA REPÚBLICA, Declaração de inconstitucionalidade, sem redução de texto, a..., null, com pedido de cautelar, null, 4, null, null, null, 2018-04-25 12:11:11, 2018-04-25 12:11:11, null, null, null, null). (SQL: insert into "processos" ("numero_judicial", "numero_alerj", "tribunal_id", "vara", "data_distribuicao", "acao_id", "juiz_id", "autor", "relator_id", "reu", "procurador_id", "estagiario_id", "assessor_id", "tipo_meio_id", "objeto", "merito", "liminar", "apensos_obs", "recurso", "observacao", "link", "updated_at", "created_at") values (5936, 5085, 2, , 2014-05-24 00:00:00, 2, 9, MESA DA ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO, 9, PRESIDENTE DA REPÚBLICA, 4, , , , Declaração de inconstitucionalidade, sem redução de texto, a fim de, em relação ao conjunto normativo decorrente do artigo 46 da Lei Federal 9478/97, do art. 2º XII e 42, § 2º da Lei Federal 12.351/2010, dar-se interpretação conforme a constituição, afirmando-se que os royalties de petróleo incidem sobre o bônus de assinatura., , com pedido de cautelar, , , , , 2018-04-25 12:11:11, 2018-04-25 12:11:11) returning "id") {"userId":25,"email":"lurodrigues@alerj.rj.gov.br","exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"tipo_meio_id\" violates not-null constraint
DETAIL:  Failing row contains (397, 5936, 5085, 2, null, 2014-05-24 00:00:00, 2, 9, null, 9, MESA DA ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO, PRESIDENTE DA REPÚBLICA, Declaração de inconstitucionalidade, sem redução de texto, a..., null, com pedido de cautelar, null, 4, null, null, null, 2018-04-25 12:11:11, 2018-04-25 12:11:11, null, null, null, null). (SQL: insert into \"processos\" (\"numero_judicial\", \"numero_alerj\", \"tribunal_id\", \"vara\", \"data_distribuicao\", \"acao_id\", \"juiz_id\", \"autor\", \"relator_id\", \"reu\", \"procurador_id\", \"estagiario_id\", \"assessor_id\", \"tipo_meio_id\", \"objeto\", \"merito\", \"liminar\", \"apensos_obs\", \"recurso\", \"observacao\", \"link\", \"updated_at\", \"created_at\") values (5936, 5085, 2, , 2014-05-24 00:00:00, 2, 9, MESA DA ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO, 9, PRESIDENTE DA REPÚBLICA, 4, , , , Declaração de inconstitucionalidade, sem redução de texto, a fim de, em relação ao conjunto normativo decorrente do artigo 46 da Lei Federal 9478/97, do art. 2º XII e 42, § 2º da Lei Federal 12.351/2010, dar-se interpretação conforme a constituição, afirmando-se que os royalties de petróleo incidem sobre o bônus de assinatura., , com pedido de cautelar, , , , , 2018-04-25 12:11:11, 2018-04-25 12:11:11) returning \"id\") at /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"tipo_meio_id\" violates not-null constraint
DETAIL:  Failing row contains (397, 5936, 5085, 2, null, 2014-05-24 00:00:00, 2, 9, null, 9, MESA DA ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO, PRESIDENTE DA REPÚBLICA, Declaração de inconstitucionalidade, sem redução de texto, a..., null, com pedido de cautelar, null, 4, null, null, null, 2018-04-25 12:11:11, 2018-04-25 12:11:11, null, null, null, null). at /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:330)
[stacktrace]
#0 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into \"pr...', Array, Object(Closure))
#1 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('insert into \"pr...', Array, Object(Closure))
#2 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\\Database\\Connection->select('insert into \"pr...', Array, false)
#3 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(20): Illuminate\\Database\\Connection->selectFromWriteConnection('insert into \"pr...', Array)
#4 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\\Database\\Query\\Processors\\PostgresProcessor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into \"pr...', Array, 'id')
#5 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1285): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Base.php(24): Illuminate\\Database\\Eloquent\\Model->save()
#10 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Controllers/Processos.php(33): App\\Data\\Repositories\\Base->createFromRequest(Object(App\\Http\\Requests\\Processo))
#11 [internal function]: App\\Http\\Controllers\\Processos->store(Object(App\\Http\\Requests\\Processo), Object(App\\Data\\Repositories\\Processos))
#12 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#13 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#14 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Processos), 'store')
#15 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#16 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#17 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Middleware/MustBeAppUser.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\MustBeAppUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#45 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#46 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#47 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#48 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#66 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#67 /home/forge/procuradoria.antoniocarlosribeiro.com/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#68 {main}
"}
```

**Comment by AlexandreFerreiraRJ** [comment]
Feito!
