### ISSUE TITLE
Erro ao tentar entrar em um processo

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/procuradoria#368]
Provavelmente relacionado a algum campo que está com data errada:

- [ ] Simular alterando manualmente as datas para '0007890'
- [ ] Resolver para não ocorrer mais a exceção
- [ ] Proteger para não deixar mais entrar com datas erradas

```
[2018-11-30 13:38:57] production.ERROR: The separation symbol could not be found
The separation symbol could not be found {"userId":25,"email":"lurodrigues@alerj.rj.gov.br","exception":"[object] (InvalidArgumentException(code: 0): The separation symbol could not be found
The separation symbol could not be found at /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/nesbot/carbon/src/Carbon/Carbon.php:909)
[stacktrace]
#0 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Base.php(175): Carbon\\Carbon::createFromFormat('d/m/Y', '0007890')
#1 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Processos.php(165): App\\Data\\Repositories\\Base->toDate('0007890')
#2 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): App\\Data\\Repositories\\Processos->App\\Data\\Repositories\\{closure}('date', 'data_distribuic...')
#3 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Processos.php(170): Illuminate\\Support\\Collection->each(Object(Closure))
#4 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): App\\Data\\Repositories\\Processos->App\\Data\\Repositories\\{closure}('0007890', 0)
#5 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Processos.php(199): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Data/Repositories/Processos.php(98): App\\Data\\Repositories\\Processos->searchString(Object(Illuminate\\Support\\Collection), Object(Illuminate\\Database\\Eloquent\\Builder))
#7 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Controllers/Processos.php(138): App\\Data\\Repositories\\Processos->filter(Object(Illuminate\\Http\\Request))
#8 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Controllers/Home.php(24): App\\Http\\Controllers\\Processos->index(Object(Illuminate\\Http\\Request))
#9 [internal function]: App\\Http\\Controllers\\Home->index(Object(Illuminate\\Http\\Request))
#10 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#12 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Home), 'index')
#13 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#14 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#15 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Middleware/SelectSubsystem.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\SelectSubsystem->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/forge/procuradoria.antoniocarlosribeiro.com/app/Http/Middleware/MustBeAppUser.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\MustBeAppUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#46 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#47 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#48 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#49 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/forge/procuradoria.antoniocarlosribeiro.com/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
```

**Comment by AlexandreFerreiraRJ** [comment]
Feitos
